name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build for multiple platforms
        run: |
          # Create build directory
          mkdir -p dist

          # Build for different platforms
          GOOS=linux GOARCH=amd64 go build -o dist/elf-cli-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o dist/elf-cli-linux-arm64
          GOOS=linux GOARCH=arm GOARM=7 go build -o dist/elf-cli-linux-armv7

          GOOS=darwin GOARCH=amd64 go build -o dist/elf-cli-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o dist/elf-cli-darwin-arm64

          GOOS=windows GOARCH=amd64 go build -o dist/elf-cli-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o dist/elf-cli-windows-arm64.exe

          # Make Linux and macOS binaries executable
          chmod +x dist/elf-cli-linux-*
          chmod +x dist/elf-cli-darwin-*

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
